from economy import Economy
economy = Economy(id = "FERNZ",
                  numeric_id = 6,
                  # as of May 2015 the following cargos must have fixed positions if used by an economy:
                  # passengers: 0, mail: 2, goods 5, food 11
                  # keep the rest of the cargos alphabetised
                  # bump the min. compatible version if this list changes
                  cargos = ['passengers',
                            'alcohol',
                            'mail',
                            'bauxite',
                            'building_materials',
                            'goods',
                            'chemicals',
                            'clay',
                            'coal',
                            'engineering_supplies',
                            'farm_supplies',
                            'food',
                            'fish',
                            'fruits',
                            'grain',
                            'gold',
                            'iron_sand',
                            'livestock',
                            'lumber',
                            'paper',
                            'metal',
                            'milk',
                            'oil',
                            'petrol',
                            'recyclables',
                            'sand',
                            'scrap_metal',
                            'salt',
                            'stone',
                            'sugar_beet',
                            'wood',
                            'wool'])
